### ISSUE TITLE
Options for font source imports

### ISSUE THREAD

**Issue by stacyk** [oddbird/accoutrement-type#3]
What is the best way to include fonts from a CDN, like Google? Or Typekit?

Currently, I think this is set up to expect font files within the project on the same server. Would be nice to clearly document other ways to import/include font files, if possible.

If it doesn't work well with these other options, can we create this feature?  If not, can we state this within the readme and/or in the file in which we import the source?

**Comment by mirisuzanne** [comment]
@stacyk working on a solution for this, to set up fonts on OddSite. How does this syntax look? or do you have another idea?

```scss
// set variant path to 'false' to stop import.
$font: (
  'my-font': {
    'normal': 'my/local/font-path', // will be imported
    'italic': false, // will not be imported
  }
);
```

The goal is that we still list the available variants (italic, bold, etc) for Herman, but the system doesn't try to import those variants.
