### ISSUE TITLE
custom font-style in the generated @font-face

### ISSUE THREAD

**Issue by ThePeach** [oddbird/accoutrement-type#9]
I'm sometimes in the situation of wanting to use a different weight for normal and bold font styles, instead of using the default weights.

This means that I would be able to achieve something along the lines of:

```CSS
@font-face {
  font-family: "Dosis";
  font-style: normal;
  font-weight: 300;
  /* .... other stuff */
}

@font-face {
  font-family: "Dosis";
  font-style: bold;
  font-weight: 600;
  /* .... other stuff */
}
```

This allows me to use that particular font-face without having to specify the weight every time.

Currently the configuration map for the font is the following:

```SASS
$fonts: (
  'heading': (
    'name': 'Dosis',
    'normal': 'Dosis-Regular',
    'bold': 'Dosis-Bold'
);
```

Which IMO should be kept as is to avoid introducing a breaking change, but it's not descriptive enough, so maybe it's possible to introduce something like:

```SASS
$fonts: (
  'heading': (
    'name': 'Dosis',
    'normal': ( 
      'file': 'Dosis-Light',
      'weight': 300
    ),
    'bold': (
      'file': 'Dosis-SemiBold',
      'weight': 600
    )
);
```

**Comment by mirisuzanne** [comment]
I think we already support:

```scss
$fonts: (
  'heading': (
    'name': 'Dosis',
    300: 'Dosis-Regular',
    600: 'Dosis-Bold',
  ),
);
```

Is that not working for you?

**Comment by ThePeach** [comment]
that only produces font-faces with different `font-weight`, the `font-style` is always the same:

```CSS
@font-face {
    font-family: 'Dosis';
    font-style: normal;
    font-weight: 300;
    src: url('Dosis-Regular') format("truetype");
}

@font-face {
    font-family: 'Dosis';
    font-style: normal;
    font-weight: 600;
    src: url('Dosis-Bold') format("truetype");
}
```

which means I have to explicitly set the `font-weight` when specifying the `font-family` in my style definition
